name: infer

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  infer:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - uses: srz-zumix/setup-infer@v1

    - name: Install prerequisites
      run: sudo apt-get install --no-install-recommends cmake

    - name: Prepare for build
      run: mkdir build

    - name: Configure cmake
      working-directory: build
      run: infer compile -- cmake -DCMAKE_BUILD_TYPE=Debug -DCXX_STANDARD_UPTO=20 ..

    - name: Run infer
      working-directory: build
      run: infer run -- make -j2 unit_test

    - name: Report infer
      uses: srz-zumix/reviewdog-action-infer@v1
      with:
        report_path: ./build/infer-out
        reporter: github-pr-review
