name: regression

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  asan:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      run: sudo apt-get install --no-install-recommends g++ cmake

    - name: Prepare for build
      run: mkdir build

    - name: Configure cmake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=address -DCXX_STANDARD_UPTO=20 ..

    - name: Build
      working-directory: build
      run: make -j2 unit_test

    - name: Run unit test
      working-directory: build
      run: ctest -j2 --output-on-failure

  ubsan:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      run: sudo apt-get install --no-install-recommends g++ cmake

    - name: Prepare for build
      run: mkdir build

    - name: Configure cmake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=undefined -DCXX_STANDARD_UPTO=20 ..

    - name: Build
      working-directory: build
      run: make -j2 unit_test

    - name: Run unit test
      working-directory: build
      run: ctest -j2 --output-on-failure

  gcc10:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      run: sudo apt-get install --no-install-recommends g++-10 cmake

    - name: Prepare for build
      run: mkdir build

    - name: Configure cmake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-10 -DCXX_STANDARD_UPTO=20 ..

    - name: Build
      working-directory: build
      run: make -j2 unit_test

    - name: Run unit test
      working-directory: build
      run: ctest -j2 --output-on-failure
